
on: push
name: CI
jobs:
  phpunit:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
          
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      with:
          fallback: 1.0.0
        
    - name: 'Get next minor version'
      id: semvers
      uses: "WyriHaximus/github-action-next-semvers@v1"
      with:
        version: ${{ steps.previoustag.outputs.tag }}
        
    - run: echo "$steps.semvers.outputs.patch"
        
